# [package]
# name = "threed"
# version = "0.1.0"
# authors = ["Julien de Charentenay <julien@charentenay.me>"]
# edition = "2021"

[workspace]
resolver = "2"
members = [
  "threedp",
  "extras/extra-rust-wasm",
  "extras/wasm-proxy",
  "extras/struct-wasm-proxy",
]

