[package]
name = "wasm-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = { version = "0" }
struct-wasm-proxy = { path = "../struct-wasm-proxy" }
serde_json = { version = "1" }
